//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace TestSspQuoteXML {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd", IsNullable=false)]
    public partial class EISExtracts {
        
        private EISExtractsBrokerDataExtract[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BrokerDataExtract")]
        public EISExtractsBrokerDataExtract[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtract {
        
        private string quoteRefField;
        
        private string clientIDField;
        
        private string quoteDateTimeField;
        
        private EISExtractsBrokerDataExtractRisk[] riskField;
        
        private EISExtractsBrokerDataExtractResultSchemesSchemeResult[][] resultField;
        
        /// <remarks/>
        public string QuoteRef {
            get {
                return this.quoteRefField;
            }
            set {
                this.quoteRefField = value;
            }
        }
        
        /// <remarks/>
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        public string QuoteDateTime {
            get {
                return this.quoteDateTimeField;
            }
            set {
                this.quoteDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Risk")]
        public EISExtractsBrokerDataExtractRisk[] Risk {
            get {
                return this.riskField;
            }
            set {
                this.riskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Schemes", typeof(EISExtractsBrokerDataExtractResultSchemesSchemeResult[]), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SchemeResult", typeof(EISExtractsBrokerDataExtractResultSchemesSchemeResult), IsNullable=false, NestingLevel=1)]
        public EISExtractsBrokerDataExtractResultSchemesSchemeResult[][] Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRisk {
        
        private string enrichmentsField;
        
        private EISExtractsBrokerDataExtractRiskControl[] controlField;
        
        private EISExtractsBrokerDataExtractRiskPolicy[] policyField;
        
        private EISExtractsBrokerDataExtractRiskAgent[] agentField;
        
        private EISExtractsBrokerDataExtractRiskProposer[] proposerField;
        
        private EISExtractsBrokerDataExtractRiskNCD[] nCDField;
        
        private EISExtractsBrokerDataExtractRiskDriversDriver[][] driversField;
        
        private EISExtractsBrokerDataExtractRiskVehiclesVehicle[][] vehiclesField;
        
        /// <remarks/>
        public string Enrichments {
            get {
                return this.enrichmentsField;
            }
            set {
                this.enrichmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Control")]
        public EISExtractsBrokerDataExtractRiskControl[] Control {
            get {
                return this.controlField;
            }
            set {
                this.controlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Policy")]
        public EISExtractsBrokerDataExtractRiskPolicy[] Policy {
            get {
                return this.policyField;
            }
            set {
                this.policyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Agent")]
        public EISExtractsBrokerDataExtractRiskAgent[] Agent {
            get {
                return this.agentField;
            }
            set {
                this.agentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Proposer")]
        public EISExtractsBrokerDataExtractRiskProposer[] Proposer {
            get {
                return this.proposerField;
            }
            set {
                this.proposerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NCD")]
        public EISExtractsBrokerDataExtractRiskNCD[] NCD {
            get {
                return this.nCDField;
            }
            set {
                this.nCDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Driver", typeof(EISExtractsBrokerDataExtractRiskDriversDriver), IsNullable=false,NestingLevel =1)]
        public EISExtractsBrokerDataExtractRiskDriversDriver[][] Drivers {
            get {
                return this.driversField;
            }
            set {
                this.driversField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Vehicle", typeof(EISExtractsBrokerDataExtractRiskVehiclesVehicle), IsNullable=false,NestingLevel =1)]
        public EISExtractsBrokerDataExtractRiskVehiclesVehicle[][] Vehicles {
            get {
                return this.vehiclesField;
            }
            set {
                this.vehiclesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskControl {
        
        private string processQuoteDetailField;
        
        private string processDocumentsField;
        
        private string processEndorsementsField;
        
        private string processUseDetailField;
        
        private string processUWNotesField;
        
        private string processWarningsField;
        
        private string processPremiumBreakdownField;
        
        private string processExcessesField;
        
        private string maxQuoteNumberField;
        
        private string polarisField;
        
        private string sSPField;
        
        private string transactionTypeField;
        
        private EISExtractsBrokerDataExtractRiskControlLOB[] lOBField;
        
        private EISExtractsBrokerDataExtractRiskControlQuotePanel[] quotePanelField;
        
        /// <remarks/>
        public string ProcessQuoteDetail {
            get {
                return this.processQuoteDetailField;
            }
            set {
                this.processQuoteDetailField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessDocuments {
            get {
                return this.processDocumentsField;
            }
            set {
                this.processDocumentsField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessEndorsements {
            get {
                return this.processEndorsementsField;
            }
            set {
                this.processEndorsementsField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessUseDetail {
            get {
                return this.processUseDetailField;
            }
            set {
                this.processUseDetailField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessUWNotes {
            get {
                return this.processUWNotesField;
            }
            set {
                this.processUWNotesField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessWarnings {
            get {
                return this.processWarningsField;
            }
            set {
                this.processWarningsField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessPremiumBreakdown {
            get {
                return this.processPremiumBreakdownField;
            }
            set {
                this.processPremiumBreakdownField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessExcesses {
            get {
                return this.processExcessesField;
            }
            set {
                this.processExcessesField = value;
            }
        }
        
        /// <remarks/>
        public string MaxQuoteNumber {
            get {
                return this.maxQuoteNumberField;
            }
            set {
                this.maxQuoteNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Polaris {
            get {
                return this.polarisField;
            }
            set {
                this.polarisField = value;
            }
        }
        
        /// <remarks/>
        public string SSP {
            get {
                return this.sSPField;
            }
            set {
                this.sSPField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LOB")]
        public EISExtractsBrokerDataExtractRiskControlLOB[] LOB {
            get {
                return this.lOBField;
            }
            set {
                this.lOBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QuotePanel")]
        public EISExtractsBrokerDataExtractRiskControlQuotePanel[] QuotePanel {
            get {
                return this.quotePanelField;
            }
            set {
                this.quotePanelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskControlLOB {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskControlQuotePanel {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskPolicy {
        
        private string coverDateField;
        
        private string voluntaryExcessField;
        
        private EISExtractsBrokerDataExtractRiskPolicyCoverType[] coverTypeField;
        
        private EISExtractsBrokerDataExtractRiskPolicyDrivingRestriction[] drivingRestrictionField;
        
        private EISExtractsBrokerDataExtractRiskPolicyVehicleUsage[] vehicleUsageField;
        
        /// <remarks/>
        public string CoverDate {
            get {
                return this.coverDateField;
            }
            set {
                this.coverDateField = value;
            }
        }
        
        /// <remarks/>
        public string VoluntaryExcess {
            get {
                return this.voluntaryExcessField;
            }
            set {
                this.voluntaryExcessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CoverType")]
        public EISExtractsBrokerDataExtractRiskPolicyCoverType[] CoverType {
            get {
                return this.coverTypeField;
            }
            set {
                this.coverTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DrivingRestriction")]
        public EISExtractsBrokerDataExtractRiskPolicyDrivingRestriction[] DrivingRestriction {
            get {
                return this.drivingRestrictionField;
            }
            set {
                this.drivingRestrictionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VehicleUsage")]
        public EISExtractsBrokerDataExtractRiskPolicyVehicleUsage[] VehicleUsage {
            get {
                return this.vehicleUsageField;
            }
            set {
                this.vehicleUsageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskPolicyCoverType {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskPolicyDrivingRestriction {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskPolicyVehicleUsage {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskAgent {
        
        private string externalAgentIDField;
        
        private string sOBField;
        
        /// <remarks/>
        public string ExternalAgentID {
            get {
                return this.externalAgentIDField;
            }
            set {
                this.externalAgentIDField = value;
            }
        }
        
        /// <remarks/>
        public string SOB {
            get {
                return this.sOBField;
            }
            set {
                this.sOBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskProposer {
        
        private string emailField;
        
        private string homeTelephoneField;
        
        private string numberOfCarsInFamilyField;
        
        private EISExtractsBrokerDataExtractRiskProposerAddress[] addressField;
        
        private EISExtractsBrokerDataExtractRiskProposerPaymentFrequency[] paymentFrequencyField;
        
        private EISExtractsBrokerDataExtractRiskProposerPreviousInsurance[] previousInsuranceField;
        
        private EISExtractsBrokerDataExtractRiskProposerProposerType[] proposerTypeField;
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string HomeTelephone {
            get {
                return this.homeTelephoneField;
            }
            set {
                this.homeTelephoneField = value;
            }
        }
        
        /// <remarks/>
        public string NumberOfCarsInFamily {
            get {
                return this.numberOfCarsInFamilyField;
            }
            set {
                this.numberOfCarsInFamilyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Address")]
        public EISExtractsBrokerDataExtractRiskProposerAddress[] Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PaymentFrequency")]
        public EISExtractsBrokerDataExtractRiskProposerPaymentFrequency[] PaymentFrequency {
            get {
                return this.paymentFrequencyField;
            }
            set {
                this.paymentFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PreviousInsurance")]
        public EISExtractsBrokerDataExtractRiskProposerPreviousInsurance[] PreviousInsurance {
            get {
                return this.previousInsuranceField;
            }
            set {
                this.previousInsuranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProposerType")]
        public EISExtractsBrokerDataExtractRiskProposerProposerType[] ProposerType {
            get {
                return this.proposerTypeField;
            }
            set {
                this.proposerTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskProposerAddress {
        
        private string addressXField;
        
        private string townField;
        
        private string countyField;
        
        private string postCodeField;
        
        /// <remarks/>
        public string AddressX {
            get {
                return this.addressXField;
            }
            set {
                this.addressXField = value;
            }
        }
        
        /// <remarks/>
        public string Town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskProposerPaymentFrequency {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskProposerPreviousInsurance {
        
        private string previousInsuranceEndDateField;
        
        private EISExtractsBrokerDataExtractRiskProposerPreviousInsurancePreviousInsurer[] previousInsurerField;
        
        /// <remarks/>
        public string PreviousInsuranceEndDate {
            get {
                return this.previousInsuranceEndDateField;
            }
            set {
                this.previousInsuranceEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PreviousInsurer")]
        public EISExtractsBrokerDataExtractRiskProposerPreviousInsurancePreviousInsurer[] PreviousInsurer {
            get {
                return this.previousInsurerField;
            }
            set {
                this.previousInsurerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskProposerPreviousInsurancePreviousInsurer {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskProposerProposerType {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskNCD {
        
        private string protectedField;
        
        private string yearsField;
        
        private EISExtractsBrokerDataExtractRiskNCDNCDType[] nCDTypeField;
        
        /// <remarks/>
        public string Protected {
            get {
                return this.protectedField;
            }
            set {
                this.protectedField = value;
            }
        }
        
        /// <remarks/>
        public string Years {
            get {
                return this.yearsField;
            }
            set {
                this.yearsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NCDType")]
        public EISExtractsBrokerDataExtractRiskNCDNCDType[] NCDType {
            get {
                return this.nCDTypeField;
            }
            set {
                this.nCDTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskNCDNCDType {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskDriversDriver {
        
        private string accessOtherCarsField;
        
        private string childrenField;
        
        private string claimsField;
        
        private string commutingField;
        
        private string convictionsField;
        
        private string criminalConvictionsField;
        
        private string disabledField;
        
        private string dOBDayField;
        
        private string dOBMonthField;
        
        private string dOBYearField;
        
        private string ageField;
        
        private string homeOwnerField;
        
        private string homeTypeField;
        
        private string nameXField;
        
        private string motorOrganisationField;
        
        private string ownOtherCarsField;
        
        private string qualificationsField;
        
        private string refusedField;
        
        private string specialTermsField;
        
        private EISExtractsBrokerDataExtractRiskDriversDriverLicence[] licenceField;
        
        private EISExtractsBrokerDataExtractRiskDriversDriverMaritalStatus[] maritalStatusField;
        
        private EISExtractsBrokerDataExtractRiskDriversDriverOccupationsOccupation[][] occupationsField;
        
        private EISExtractsBrokerDataExtractRiskDriversDriverRelationshipToProposer[] relationshipToProposerField;
        
        private EISExtractsBrokerDataExtractRiskDriversDriverResidency[] residencyField;
        
        private EISExtractsBrokerDataExtractRiskDriversDriverSex[] sexField;
        
        private EISExtractsBrokerDataExtractRiskDriversDriverTitle[] titleField;
        
        private EISExtractsBrokerDataExtractRiskDriversDriverUsageFrequency[] usageFrequencyField;
        
        /// <remarks/>
        public string AccessOtherCars {
            get {
                return this.accessOtherCarsField;
            }
            set {
                this.accessOtherCarsField = value;
            }
        }
        
        /// <remarks/>
        public string Children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
        
        /// <remarks/>
        public string Claims {
            get {
                return this.claimsField;
            }
            set {
                this.claimsField = value;
            }
        }
        
        /// <remarks/>
        public string Commuting {
            get {
                return this.commutingField;
            }
            set {
                this.commutingField = value;
            }
        }
        
        /// <remarks/>
        public string Convictions {
            get {
                return this.convictionsField;
            }
            set {
                this.convictionsField = value;
            }
        }
        
        /// <remarks/>
        public string CriminalConvictions {
            get {
                return this.criminalConvictionsField;
            }
            set {
                this.criminalConvictionsField = value;
            }
        }
        
        /// <remarks/>
        public string Disabled {
            get {
                return this.disabledField;
            }
            set {
                this.disabledField = value;
            }
        }
        
        /// <remarks/>
        public string DOBDay {
            get {
                return this.dOBDayField;
            }
            set {
                this.dOBDayField = value;
            }
        }
        
        /// <remarks/>
        public string DOBMonth {
            get {
                return this.dOBMonthField;
            }
            set {
                this.dOBMonthField = value;
            }
        }
        
        /// <remarks/>
        public string DOBYear {
            get {
                return this.dOBYearField;
            }
            set {
                this.dOBYearField = value;
            }
        }
        
        /// <remarks/>
        public string Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        public string HomeOwner {
            get {
                return this.homeOwnerField;
            }
            set {
                this.homeOwnerField = value;
            }
        }
        
        /// <remarks/>
        public string HomeType {
            get {
                return this.homeTypeField;
            }
            set {
                this.homeTypeField = value;
            }
        }
        
        /// <remarks/>
        public string NameX {
            get {
                return this.nameXField;
            }
            set {
                this.nameXField = value;
            }
        }
        
        /// <remarks/>
        public string MotorOrganisation {
            get {
                return this.motorOrganisationField;
            }
            set {
                this.motorOrganisationField = value;
            }
        }
        
        /// <remarks/>
        public string OwnOtherCars {
            get {
                return this.ownOtherCarsField;
            }
            set {
                this.ownOtherCarsField = value;
            }
        }
        
        /// <remarks/>
        public string Qualifications {
            get {
                return this.qualificationsField;
            }
            set {
                this.qualificationsField = value;
            }
        }
        
        /// <remarks/>
        public string Refused {
            get {
                return this.refusedField;
            }
            set {
                this.refusedField = value;
            }
        }
        
        /// <remarks/>
        public string SpecialTerms {
            get {
                return this.specialTermsField;
            }
            set {
                this.specialTermsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Licence")]
        public EISExtractsBrokerDataExtractRiskDriversDriverLicence[] Licence {
            get {
                return this.licenceField;
            }
            set {
                this.licenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaritalStatus")]
        public EISExtractsBrokerDataExtractRiskDriversDriverMaritalStatus[] MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Occupation", typeof(EISExtractsBrokerDataExtractRiskDriversDriverOccupationsOccupation), IsNullable=false,NestingLevel =1)]
        public EISExtractsBrokerDataExtractRiskDriversDriverOccupationsOccupation[][] Occupations {
            get {
                return this.occupationsField;
            }
            set {
                this.occupationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RelationshipToProposer")]
        public EISExtractsBrokerDataExtractRiskDriversDriverRelationshipToProposer[] RelationshipToProposer {
            get {
                return this.relationshipToProposerField;
            }
            set {
                this.relationshipToProposerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Residency")]
        public EISExtractsBrokerDataExtractRiskDriversDriverResidency[] Residency {
            get {
                return this.residencyField;
            }
            set {
                this.residencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sex")]
        public EISExtractsBrokerDataExtractRiskDriversDriverSex[] Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Title")]
        public EISExtractsBrokerDataExtractRiskDriversDriverTitle[] Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UsageFrequency")]
        public EISExtractsBrokerDataExtractRiskDriversDriverUsageFrequency[] UsageFrequency {
            get {
                return this.usageFrequencyField;
            }
            set {
                this.usageFrequencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskDriversDriverLicence {
        
        private string licenceDateField;
        
        private string licenceRestrictionsField;
        
        private EISExtractsBrokerDataExtractRiskDriversDriverLicenceLicenceType[] licenceTypeField;
        
        /// <remarks/>
        public string LicenceDate {
            get {
                return this.licenceDateField;
            }
            set {
                this.licenceDateField = value;
            }
        }
        
        /// <remarks/>
        public string LicenceRestrictions {
            get {
                return this.licenceRestrictionsField;
            }
            set {
                this.licenceRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LicenceType")]
        public EISExtractsBrokerDataExtractRiskDriversDriverLicenceLicenceType[] LicenceType {
            get {
                return this.licenceTypeField;
            }
            set {
                this.licenceTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskDriversDriverLicenceLicenceType {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskDriversDriverMaritalStatus {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskDriversDriverOccupationsOccupation {
        
        private EISExtractsBrokerDataExtractRiskDriversDriverOccupationsOccupationBusiness[] businessField;
        
        private EISExtractsBrokerDataExtractRiskDriversDriverOccupationsOccupationEmploymentStatus[] employmentStatusField;
        
        private EISExtractsBrokerDataExtractRiskDriversDriverOccupationsOccupationOccupationType[] occupationTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Business")]
        public EISExtractsBrokerDataExtractRiskDriversDriverOccupationsOccupationBusiness[] Business {
            get {
                return this.businessField;
            }
            set {
                this.businessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmploymentStatus")]
        public EISExtractsBrokerDataExtractRiskDriversDriverOccupationsOccupationEmploymentStatus[] EmploymentStatus {
            get {
                return this.employmentStatusField;
            }
            set {
                this.employmentStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OccupationType")]
        public EISExtractsBrokerDataExtractRiskDriversDriverOccupationsOccupationOccupationType[] OccupationType {
            get {
                return this.occupationTypeField;
            }
            set {
                this.occupationTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskDriversDriverOccupationsOccupationBusiness {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskDriversDriverOccupationsOccupationEmploymentStatus {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskDriversDriverOccupationsOccupationOccupationType {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskDriversDriverRelationshipToProposer {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskDriversDriverResidency {
        
        private string birthCountryField;
        
        private string dateToUKDayField;
        
        private string dateToUKMonthField;
        
        private string dateToUkYearField;
        
        private string permanentField;
        
        private string yearsField;
        
        /// <remarks/>
        public string BirthCountry {
            get {
                return this.birthCountryField;
            }
            set {
                this.birthCountryField = value;
            }
        }
        
        /// <remarks/>
        public string DateToUKDay {
            get {
                return this.dateToUKDayField;
            }
            set {
                this.dateToUKDayField = value;
            }
        }
        
        /// <remarks/>
        public string DateToUKMonth {
            get {
                return this.dateToUKMonthField;
            }
            set {
                this.dateToUKMonthField = value;
            }
        }
        
        /// <remarks/>
        public string DateToUkYear {
            get {
                return this.dateToUkYearField;
            }
            set {
                this.dateToUkYearField = value;
            }
        }
        
        /// <remarks/>
        public string Permanent {
            get {
                return this.permanentField;
            }
            set {
                this.permanentField = value;
            }
        }
        
        /// <remarks/>
        public string Years {
            get {
                return this.yearsField;
            }
            set {
                this.yearsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskDriversDriverSex {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskDriversDriverTitle {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskDriversDriverUsageFrequency {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskVehiclesVehicle {
        
        private string businessMilesField;
        
        private string commercialVehicleTypeField;
        
        private string vehicleColourField;
        
        private string dateManufacturedField;
        
        private string datePurchasedField;
        
        private string dateRegisteredField;
        
        private string engineSizeField;
        
        private string importedField;
        
        private string keptAtProposerAddressField;
        
        private string makeField;
        
        private string modelField;
        
        private string modificationsField;
        
        private string motorcycleField;
        
        private string numberDoorsField;
        
        private string numberSeatsField;
        
        private string pleasureMilesField;
        
        private string registrationField;
        
        private string valueField;
        
        private string valueTypeField;
        
        private string vehicleFinishField;
        
        private EISExtractsBrokerDataExtractRiskVehiclesVehicleBodyType[] bodyTypeField;
        
        private EISExtractsBrokerDataExtractRiskVehiclesVehicleDriveSide[] driveSideField;
        
        private EISExtractsBrokerDataExtractRiskVehiclesVehicleFuel[] fuelField;
        
        private EISExtractsBrokerDataExtractRiskVehiclesVehicleKeptAddress[] keptAddressField;
        
        private EISExtractsBrokerDataExtractRiskVehiclesVehicleKeptLocation[] keptLocationField;
        
        private EISExtractsBrokerDataExtractRiskVehiclesVehicleSecurityDevicesSecurityDevice[][] securityDevicesField;
        
        private EISExtractsBrokerDataExtractRiskVehiclesVehicleTransmissionType[] transmissionTypeField;
        
        private EISExtractsBrokerDataExtractRiskVehiclesVehicleVehicleDetails[] vehicleDetailsField;
        
        private EISExtractsBrokerDataExtractRiskVehiclesVehicleVehicleKeeper[] vehicleKeeperField;
        
        private EISExtractsBrokerDataExtractRiskVehiclesVehicleVehicleOwner[] vehicleOwnerField;
        
        /// <remarks/>
        public string BusinessMiles {
            get {
                return this.businessMilesField;
            }
            set {
                this.businessMilesField = value;
            }
        }
        
        /// <remarks/>
        public string CommercialVehicleType {
            get {
                return this.commercialVehicleTypeField;
            }
            set {
                this.commercialVehicleTypeField = value;
            }
        }
        
        /// <remarks/>
        public string VehicleColour {
            get {
                return this.vehicleColourField;
            }
            set {
                this.vehicleColourField = value;
            }
        }
        
        /// <remarks/>
        public string DateManufactured {
            get {
                return this.dateManufacturedField;
            }
            set {
                this.dateManufacturedField = value;
            }
        }
        
        /// <remarks/>
        public string DatePurchased {
            get {
                return this.datePurchasedField;
            }
            set {
                this.datePurchasedField = value;
            }
        }
        
        /// <remarks/>
        public string DateRegistered {
            get {
                return this.dateRegisteredField;
            }
            set {
                this.dateRegisteredField = value;
            }
        }
        
        /// <remarks/>
        public string EngineSize {
            get {
                return this.engineSizeField;
            }
            set {
                this.engineSizeField = value;
            }
        }
        
        /// <remarks/>
        public string Imported {
            get {
                return this.importedField;
            }
            set {
                this.importedField = value;
            }
        }
        
        /// <remarks/>
        public string KeptAtProposerAddress {
            get {
                return this.keptAtProposerAddressField;
            }
            set {
                this.keptAtProposerAddressField = value;
            }
        }
        
        /// <remarks/>
        public string Make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string Modifications {
            get {
                return this.modificationsField;
            }
            set {
                this.modificationsField = value;
            }
        }
        
        /// <remarks/>
        public string Motorcycle {
            get {
                return this.motorcycleField;
            }
            set {
                this.motorcycleField = value;
            }
        }
        
        /// <remarks/>
        public string NumberDoors {
            get {
                return this.numberDoorsField;
            }
            set {
                this.numberDoorsField = value;
            }
        }
        
        /// <remarks/>
        public string NumberSeats {
            get {
                return this.numberSeatsField;
            }
            set {
                this.numberSeatsField = value;
            }
        }
        
        /// <remarks/>
        public string PleasureMiles {
            get {
                return this.pleasureMilesField;
            }
            set {
                this.pleasureMilesField = value;
            }
        }
        
        /// <remarks/>
        public string Registration {
            get {
                return this.registrationField;
            }
            set {
                this.registrationField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string ValueType {
            get {
                return this.valueTypeField;
            }
            set {
                this.valueTypeField = value;
            }
        }
        
        /// <remarks/>
        public string VehicleFinish {
            get {
                return this.vehicleFinishField;
            }
            set {
                this.vehicleFinishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BodyType")]
        public EISExtractsBrokerDataExtractRiskVehiclesVehicleBodyType[] BodyType {
            get {
                return this.bodyTypeField;
            }
            set {
                this.bodyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DriveSide")]
        public EISExtractsBrokerDataExtractRiskVehiclesVehicleDriveSide[] DriveSide {
            get {
                return this.driveSideField;
            }
            set {
                this.driveSideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fuel")]
        public EISExtractsBrokerDataExtractRiskVehiclesVehicleFuel[] Fuel {
            get {
                return this.fuelField;
            }
            set {
                this.fuelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeptAddress")]
        public EISExtractsBrokerDataExtractRiskVehiclesVehicleKeptAddress[] KeptAddress {
            get {
                return this.keptAddressField;
            }
            set {
                this.keptAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeptLocation")]
        public EISExtractsBrokerDataExtractRiskVehiclesVehicleKeptLocation[] KeptLocation {
            get {
                return this.keptLocationField;
            }
            set {
                this.keptLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SecurityDevice", typeof(EISExtractsBrokerDataExtractRiskVehiclesVehicleSecurityDevicesSecurityDevice), IsNullable=false,NestingLevel=1)]
        public EISExtractsBrokerDataExtractRiskVehiclesVehicleSecurityDevicesSecurityDevice[][] SecurityDevices {
            get {
                return this.securityDevicesField;
            }
            set {
                this.securityDevicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransmissionType")]
        public EISExtractsBrokerDataExtractRiskVehiclesVehicleTransmissionType[] TransmissionType {
            get {
                return this.transmissionTypeField;
            }
            set {
                this.transmissionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VehicleDetails")]
        public EISExtractsBrokerDataExtractRiskVehiclesVehicleVehicleDetails[] VehicleDetails {
            get {
                return this.vehicleDetailsField;
            }
            set {
                this.vehicleDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VehicleKeeper")]
        public EISExtractsBrokerDataExtractRiskVehiclesVehicleVehicleKeeper[] VehicleKeeper {
            get {
                return this.vehicleKeeperField;
            }
            set {
                this.vehicleKeeperField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VehicleOwner")]
        public EISExtractsBrokerDataExtractRiskVehiclesVehicleVehicleOwner[] VehicleOwner {
            get {
                return this.vehicleOwnerField;
            }
            set {
                this.vehicleOwnerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskVehiclesVehicleBodyType {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskVehiclesVehicleDriveSide {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskVehiclesVehicleFuel {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskVehiclesVehicleKeptAddress {
        
        private string addressXField;
        
        private string townField;
        
        private string countyField;
        
        private string postCodeField;
        
        /// <remarks/>
        public string AddressX {
            get {
                return this.addressXField;
            }
            set {
                this.addressXField = value;
            }
        }
        
        /// <remarks/>
        public string Town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskVehiclesVehicleKeptLocation {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskVehiclesVehicleSecurityDevicesSecurityDevice {
        
        private EISExtractsBrokerDataExtractRiskVehiclesVehicleSecurityDevicesSecurityDeviceDeviceFitter[] deviceFitterField;
        
        private EISExtractsBrokerDataExtractRiskVehiclesVehicleSecurityDevicesSecurityDeviceDeviceType[] deviceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeviceFitter")]
        public EISExtractsBrokerDataExtractRiskVehiclesVehicleSecurityDevicesSecurityDeviceDeviceFitter[] DeviceFitter {
            get {
                return this.deviceFitterField;
            }
            set {
                this.deviceFitterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeviceType")]
        public EISExtractsBrokerDataExtractRiskVehiclesVehicleSecurityDevicesSecurityDeviceDeviceType[] DeviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskVehiclesVehicleSecurityDevicesSecurityDeviceDeviceFitter {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskVehiclesVehicleSecurityDevicesSecurityDeviceDeviceType {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskVehiclesVehicleTransmissionType {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskVehiclesVehicleVehicleDetails {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskVehiclesVehicleVehicleKeeper {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractRiskVehiclesVehicleVehicleOwner {
        
        private string descriptionField;
        
        private string abiField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Abi {
            get {
                return this.abiField;
            }
            set {
                this.abiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ssp.web.services/MotorAggregator/schemas/PMQuoteData.xsd")]
    public partial class EISExtractsBrokerDataExtractResultSchemesSchemeResult {
        
        private string schemeNumberField;
        
        private string preFlexPremiumField;
        
        private string totalPremiumField;
        
        private string commissionAmountField;
        
        private string netPremiumField;
        
        private string iPTAmountField;
        
        private string schemeRawDataField;
        
        private string enrichmentField;
        
        /// <remarks/>
        public string SchemeNumber {
            get {
                return this.schemeNumberField;
            }
            set {
                this.schemeNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PreFlexPremium {
            get {
                return this.preFlexPremiumField;
            }
            set {
                this.preFlexPremiumField = value;
            }
        }
        
        /// <remarks/>
        public string TotalPremium {
            get {
                return this.totalPremiumField;
            }
            set {
                this.totalPremiumField = value;
            }
        }
        
        /// <remarks/>
        public string CommissionAmount {
            get {
                return this.commissionAmountField;
            }
            set {
                this.commissionAmountField = value;
            }
        }
        
        /// <remarks/>
        public string NetPremium {
            get {
                return this.netPremiumField;
            }
            set {
                this.netPremiumField = value;
            }
        }
        
        /// <remarks/>
        public string IPTAmount {
            get {
                return this.iPTAmountField;
            }
            set {
                this.iPTAmountField = value;
            }
        }
        
        /// <remarks/>
        public string SchemeRawData {
            get {
                return this.schemeRawDataField;
            }
            set {
                this.schemeRawDataField = value;
            }
        }
        
        /// <remarks/>
        public string Enrichment {
            get {
                return this.enrichmentField;
            }
            set {
                this.enrichmentField = value;
            }
        }
    }
}
